;;; evil-gamepad-test.el --- Tests for evil-gamepad -*- lexical-binding: t; -*-

(require 'ert)
(require 'evil)
(require 'evil-gamepad)

(ert-deftest evil-gamepad-mode-binds-normal-movement-keys ()
  (let ((evil-normal-state-map (make-sparse-keymap))
        (evil-visual-state-map (make-sparse-keymap)))
    (evil-gamepad-mode 1)
    (should (eq (lookup-key evil-normal-state-map (kbd "a"))
                #'evil-backward-char))
    (should (eq (lookup-key evil-normal-state-map (kbd "d"))
                #'evil-forward-char))
    (should (eq (lookup-key evil-normal-state-map (kbd "w"))
                #'evil-previous-line))
    (should (eq (lookup-key evil-normal-state-map (kbd "s"))
                #'evil-next-line))
    (evil-gamepad-mode -1)))

(ert-deftest evil-gamepad-mode-binds-normal-action-keys ()
  (let ((evil-normal-state-map (make-sparse-keymap))
        (evil-visual-state-map (make-sparse-keymap)))
    (evil-gamepad-mode 1)
    (should (eq (lookup-key evil-normal-state-map (kbd "h"))
                #'evil-delete-backward-char-and-join))
    (should (eq (lookup-key evil-normal-state-map (kbd "k"))
                #'evil-delete-char))
    (should (eq (lookup-key evil-normal-state-map (kbd "l"))
                #'evil-append))
    (evil-gamepad-mode -1)))

(ert-deftest evil-gamepad-mode-binds-visual-movement-keys ()
  (let ((evil-normal-state-map (make-sparse-keymap))
        (evil-visual-state-map (make-sparse-keymap)))
    (evil-gamepad-mode 1)
    (should (eq (lookup-key evil-visual-state-map (kbd "a"))
                #'evil-backward-char))
    (should (eq (lookup-key evil-visual-state-map (kbd "d"))
                #'evil-forward-char))
    (should (eq (lookup-key evil-visual-state-map (kbd "w"))
                #'evil-previous-line))
    (should (eq (lookup-key evil-visual-state-map (kbd "s"))
                #'evil-next-line))
    (evil-gamepad-mode -1)))

(ert-deftest evil-gamepad-mode-restores-previous-bindings ()
  (let ((evil-normal-state-map (make-sparse-keymap))
        (evil-visual-state-map (make-sparse-keymap)))
    (define-key evil-normal-state-map (kbd "a") #'beginning-of-buffer)
    (define-key evil-visual-state-map (kbd "a") #'mark-whole-buffer)
    (evil-gamepad-mode 1)
    (evil-gamepad-mode -1)
    (should (eq (lookup-key evil-normal-state-map (kbd "a"))
                #'beginning-of-buffer))
    (should (eq (lookup-key evil-visual-state-map (kbd "a"))
                #'mark-whole-buffer))))

(ert-deftest evil-gamepad-mode-applies-search-tweaks-when-enabled ()
  (let ((evil-normal-state-map (make-sparse-keymap))
        (evil-visual-state-map (make-sparse-keymap))
        (evil-search-module 'isearch)
        (evil-symbol-word-search nil)
        (evil-gamepad-enable-search-tweaks t))
    (evil-gamepad-mode 1)
    (should evil-symbol-word-search)
    (should (eq evil-search-module 'evil-search))
    (evil-gamepad-mode -1)
    (should-not evil-symbol-word-search)
    (should (eq evil-search-module 'isearch))))
